import { Society } from './types';

export const mockSocieties: Society[] = [
  {
    id: '1',
    name: 'Sunrise Heights CHS Ltd',
    address: '123 MG Road, Andheri West',
    city: 'Mumbai',
    totalUnits: 120,
    yearBuilt: 2015,
    overallLevel: 4,
    leedScore: 72,
    lastAssessed: '2025-12-15',
    scores: {
      structuralSafety: 4,
      fireSafety: 4,
      waterManagement: 5,
      electricalSystems: 4,
      wasteManagement: 3,
      greenBuilding: 4,
      accessibility: 3,
      securitySystems: 5,
      commonAreaMaintenance: 4,
      governance: 4,
    },
    compliance: [
      { id: 'c1', name: 'Earthquake Resistance Certificate (Zone 3)', status: 'valid', issuedDate: '2024-01-10', expiryDate: '2027-01-10', mandatory: true, category: 'Structural' },
      { id: 'c2', name: 'Fire Safety NOC', status: 'valid', issuedDate: '2024-06-01', expiryDate: '2026-06-01', mandatory: true, category: 'Fire Safety' },
      { id: 'c3', name: 'Occupancy Certificate', status: 'valid', issuedDate: '2015-08-01', mandatory: true, category: 'Legal' },
      { id: 'c4', name: 'LEED Green Building Certification', status: 'pending', mandatory: false, category: 'Green Building' },
      { id: 'c5', name: 'Lift/Elevator Safety Certificate', status: 'valid', issuedDate: '2025-03-01', expiryDate: '2026-03-01', mandatory: true, category: 'Utilities' },
      { id: 'c6', name: 'Water Quality Certificate', status: 'expired', issuedDate: '2023-01-01', expiryDate: '2025-01-01', mandatory: true, category: 'Utilities' },
    ],
  },
  {
    id: '2',
    name: 'Green Valley Apartments CHS Ltd',
    address: '45 Baner Road',
    city: 'Pune',
    totalUnits: 80,
    yearBuilt: 2019,
    overallLevel: 5,
    leedScore: 91,
    lastAssessed: '2026-01-20',
    scores: {
      structuralSafety: 5,
      fireSafety: 5,
      waterManagement: 5,
      electricalSystems: 5,
      wasteManagement: 5,
      greenBuilding: 5,
      accessibility: 4,
      securitySystems: 5,
      commonAreaMaintenance: 5,
      governance: 5,
    },
    compliance: [
      { id: 'c7', name: 'Earthquake Resistance Certificate (Zone 3)', status: 'valid', issuedDate: '2024-05-15', expiryDate: '2027-05-15', mandatory: true, category: 'Structural' },
      { id: 'c8', name: 'LEED Green Building Certification', status: 'valid', issuedDate: '2024-08-01', expiryDate: '2029-08-01', mandatory: false, category: 'Green Building' },
      { id: 'c9', name: 'Fire Safety NOC', status: 'valid', issuedDate: '2025-01-01', expiryDate: '2027-01-01', mandatory: true, category: 'Fire Safety' },
    ],
  },
  {
    id: '3',
    name: 'Lakeside Towers CHS Ltd',
    address: '78 Whitefield',
    city: 'Bangalore',
    totalUnits: 200,
    yearBuilt: 2010,
    overallLevel: 2,
    leedScore: 35,
    lastAssessed: '2025-09-10',
    scores: {
      structuralSafety: 3,
      fireSafety: 2,
      waterManagement: 2,
      electricalSystems: 2,
      wasteManagement: 1,
      greenBuilding: 1,
      accessibility: 2,
      securitySystems: 3,
      commonAreaMaintenance: 2,
      governance: 2,
    },
    compliance: [
      { id: 'c10', name: 'Earthquake Resistance Certificate (Zone 3)', status: 'expired', issuedDate: '2020-01-01', expiryDate: '2023-01-01', mandatory: true, category: 'Structural' },
      { id: 'c11', name: 'Fire Safety NOC', status: 'expired', issuedDate: '2021-06-01', expiryDate: '2023-06-01', mandatory: true, category: 'Fire Safety' },
      { id: 'c12', name: 'Occupancy Certificate', status: 'valid', issuedDate: '2010-12-01', mandatory: true, category: 'Legal' },
    ],
  },
];
